// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Load(arg1:main.ExecHandle):Promise<main.Job>;

export function Register(arg1:main.Entry):Promise<main.ExecHandle>;

export function Run(arg1:main.ExecHandle):Promise<void>;
