// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function Get() {
  return window['go']['main']['App']['Get']();
}

export function Launch(arg1) {
  return window['go']['main']['App']['Launch'](arg1);
}
