// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:main.Job):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function Get():Promise<Array<main.Job>>;

export function Launch(arg1:main.Job):Promise<void>;
