// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Load(arg1) {
  return window['go']['main']['App']['Load'](arg1);
}

export function LoadAll() {
  return window['go']['main']['App']['LoadAll']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}
